-- scripts/ops/investcock-drop.sql
-- 투자콕 50개 테이블을 셀러 DB에서 지운다(2026-09-25 사용자 승인). 새 무료 조직 Supabase로 이전·대조 완료 뒤에만 실행한다.
-- 덤프: /Volumes/Mac_SSD/backup/investcock/investcock-20260925-1621.sql
-- restrict: 다른 테이블이 참조하면 전체 롤백된다(cascade로 바꾸지 않는다).
begin;
drop table
  public.users,
  public.api_keys,
  public.portfolios,
  public.holdings,
  public.rebalance_logs,
  public.trade_journals,
  public.refresh_tokens,
  public.ai_analysis_results,
  public.login_attempts,
  public.kis_tokens,
  public.account_settings,
  public.tax_profiles,
  public.tax_account_snapshots,
  public.tax_contributions,
  public.investment_plans,
  public.ic_rules,
  public.ic_budget_events,
  public.ic_llm_call_logs,
  public.ic_user_phase_selections,
  public.rebalance_snapshots,
  public.snapshot_actions,
  public.deposit_logs,
  public.recommend_universe,
  public.recommend_factor_snapshot,
  public.agent_debates,
  public.recommendations,
  public.recommendation_scores,
  public.backtest_runs,
  public.backtest_windows,
  public.backtest_equity_curve,
  public.backtest_trades,
  public.macro_indicators,
  public.regime_history,
  public.user_risk_profiles,
  public.user_cash_needs,
  public.user_tax_info,
  public.ticker_signals_daily,
  public.market_signals_daily,
  public.decision_journal,
  public.decision_reviews,
  public.paper_portfolio,
  public.paper_position,
  public.paper_trade,
  public.paper_trade_review,
  public.paper_learning,
  public.telegram_config,
  public.job_run_log,
  public.watchlists,
  public.watch_alerts,
  public.weekly_screener_picks
  restrict;
commit;
