import type { FrameMeta } from '@/types/frames';

export const FRAME_DEFINITIONS: FrameMeta[] = [
  {
    type: 'hero',
    label: 'Hero',
    labelKo: '히어로',
    description: '시선을 끄는 강력한 카피와 상품 요약',
    sortOrder: 0,
  },
  {
    type: 'pain_point',
    label: 'Pain Point',
    labelKo: '불편함 공감',
    description: '고객이 겪는 불편함 공감',
    sortOrder: 1,
  },
  {
    type: 'solution',
    label: 'Solution',
    labelKo: '해결책 제시',
    description: '이 제품이 어떻게 문제를 해결하는지',
    sortOrder: 2,
  },
  {
    type: 'usp',
    label: 'USP',
    labelKo: '핵심 차별점',
    description: '타사 제품과의 비교 우위 포인트',
    sortOrder: 3,
  },
  {
    type: 'detail_1',
    label: 'Detail 1',
    labelKo: '기능/소재',
    description: '첫 번째 주요 특징 상세 설명',
    sortOrder: 4,
  },
  {
    type: 'detail_2',
    label: 'Detail 2',
    labelKo: '디자인/감성',
    description: '두 번째 주요 특징 상세 설명',
    sortOrder: 5,
  },
  {
    type: 'how_to_use',
    label: 'How to Use',
    labelKo: '사용 방법',
    description: '직관적이고 쉬운 사용법 안내',
    sortOrder: 6,
  },
  {
    type: 'before_after',
    label: 'Before & After',
    labelKo: '비포&애프터',
    description: '제품 사용 전/후의 극적인 변화',
    sortOrder: 7,
  },
  {
    type: 'target',
    label: 'Target',
    labelKo: '타겟 고객',
    description: '이런 분들께 강력 추천합니다',
    sortOrder: 8,
  },
  {
    type: 'spec',
    label: 'Spec',
    labelKo: '스펙/사이즈',
    description: '정확한 수치, 재질, 인증 내역',
    sortOrder: 9,
  },
  {
    type: 'faq',
    label: 'FAQ',
    labelKo: '자주 묻는 질문',
    description: '구매 전 자주 묻는 3가지',
    sortOrder: 10,
  },
  {
    type: 'social_proof',
    label: 'Social Proof',
    labelKo: '신뢰도',
    description: '리뷰 또는 전문가 추천사',
    sortOrder: 11,
  },
  {
    type: 'cta',
    label: 'CTA',
    labelKo: '구매 유도',
    description: '당장 구매해야 하는 이유',
    sortOrder: 12,
  },
];
